### ISSUE TITLE
[dx] ts-node-dev stopped working in Docker

### ISSUE THREAD

**Issue by mattwynne** [SmartBear/git-en-boite#23]
I'm sure this was working a few days ago, but now, when the app tries to start in docker-compose on my dev machine, I see this:

```
Using ts-node version 8.8.1, typescript version 3.8.3
app_1       | TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
app_1       |     at Object.watch (fs.js:1441:11)
app_1       |     at add (/app/node_modules/filewatcher/index.js:74:34)
app_1       |     at /app/node_modules/filewatcher/index.js:93:5
app_1       |     at FSReqCallback.oncomplete (fs.js:176:5)
app_1       | child_process.js:650
app_1       |     throw err;
app_1       |     ^
app_1       |
app_1       | Error: Command failed: ts-node-dev src/server.ts
```

I don't need this, so I'm going to remove it for now as it's not what I was planning to work on.

If someone wants to figure out how to use Docker for development, that's fine, but as well as fixing this we'll also need to set up a volume to the source code, etc. So it's a little project.

**Comment by mattwynne** [comment]
Not a problem for us at the moment. #wontfix.
